# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: nuxt3-tailwind-starter
metadata:
  template: nuxt3-tailwind-starter@0.0.1-beta
  
infra:
  provider: bicep
  path: infra

services:
  web:
    project: .
    language: js
    host: staticwebapp
    hooks:
      prebuild:
        shell: pwsh
        run: npm ci
        continueOnError: false
      build:
        shell: pwsh  
        run: npm run generate
        continueOnError: false
